language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install

before_script:
  - composer install
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - npm prune
  - phpenv versions
  - npm --version
  - node --version

script:
  - grunt phpcs
  - grunt default
